language: python
python:
  - 3.9.1
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro-fgomes/tests --cov=libpythonpro-fgomes
after_success:
  - codecov