language: python
python:
  - 3.9.1
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro_fgomes/tests --cov=libpythonpro_fgomes
after_success:
  - codecov